images:
  tags:
    bootstrap: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    db_init: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    db_drop: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    ks_user: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    ks_service: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    ks_endpoints: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_db_sync: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_api: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_cfn: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_cloudwatch: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_engine: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_engine_cleaner: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"
    heat_purge_deleted: "quay.io/airshipit/heat:${OPENSTACK_RELEASE}-${OPENSTACK_DIST}"

endpoints:
  identity:
    auth:
      admin:
        password: ${keystone_admin_password}
      heat:
        password: ${heat_admin_password}
      heat_trustee:
        password: ${heat_trustee_password}
      heat_stack_user:
        password: ${heat_stack_user_password}
      test:
        password: ${heat_test_password}
  oslo_db:
    auth:
      admin:
        password: ${mariadb_root_password}
      heat:
        password: ${heat_db_password}
  oslo_messaging:
    auth:
      admin:
        password: ${rabbitmq_admin_password}
      heat:
        password: ${heat_rabbitmq_password}
    statefulset:
      replicas: 3
  orchestration:
    host_fqdn_override:
      public:
        host: "heat.${HOST}"
        tls:
          secretName: ingress-cert
          issuerRef:
            name: letsencrypt
            kind: ClusterIssuer
    scheme:
      public: https
    port:
      api:
        public: 443
  cloudformation:
    host_fqdn_override:
      public:
        host: "cloudformation.${HOST}"
        tls:
          secretName: ingress-cert
          issuerRef:
            name: letsencrypt
            kind: ClusterIssuer
    scheme:
      public: https
    port:
      api:
        public: 443

secrets:
  tls:
    orchestration:
      api:
        public: ingress-cert
    cloudformation:
      cfn:
        public: ingress-cert