apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  releaseName: rook-ceph-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      version: ${ROOK_RELEASE}
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: rook-ceph
  dependsOn:
    - name: rook-ceph
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-values
