apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
resources:
  - namespace.yaml
  - gitrepository.yaml
  - openstack-cluster-issuer
  - openstack-certificate
  - ceph-adapter-rook
  - rabbitmq
  - mariadb
  - postgresql
#  - mariadb-operator
#  - mariadb-cluster
  - memcached
  - valkey