controller:
  kind: Deployment
  admissionWebhooks:
    enabled: false
  scope:
    enabled: true
  service: 
    enabled: true
    annotations:
      kube-vip.io/loadbalancerIPs: "${KUBE_VIP_SERVICE_IP}"
    loadBalancerClass: "kube-vip.io/kube-vip-class"
  ingressClassResource:
    name: nginx 
    controllerValue: "k8s.io/ingress-nginx"
    default: false
  ingressClass: nginx 
  labels:
    app: ingress-api