global:
  security:
    allowInsecureImages: true

image:
  registry: quay.io
  repository: thanos/thanos
  tag: v0.39.2

existingObjstoreSecret: "prometheus-stack-kube-prom-prometheus"
existingObjstoreSecretItems: 
    - key: object-storage-configs.yaml
      path: objstore.yml
storegateway:
  enabled: true
queryFrontend:
  replicaCount: 2
query:
  replicaCount: 2
  dnsDiscovery:
    enabled: true
    sidecarsService: "prometheus-stack-kube-prom-thanos-discovery"
    sidecarsNamespace: "monitoring"
compactor:
  enabled: true
  retentionResolutionRaw: 10d
  retentionResolution5m: 10d
  retentionResolution1h: 10y
  persistence:
    size: 10Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
