apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: external-dns
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:LXwfH8B2Sh4y72t1tastabZfeIAAXRU=,iv:EWtTHFtUBOIh3CQ9bbCub7iCKeEVh1wUahrAwNcsF+U=,tag:7T2itn0T2iYaxwLl6I79gg==,type:str]
sops:
    lastmodified: "2025-11-25T19:19:36Z"
    mac: ENC[AES256_GCM,data:8EuEK3UdmTfPomydlUKJ0QLetI5YUcbpVVBrdqRu+wOit0sCL4eDJWh1Z/uIJzfyk+DBBj0LgV4x6d0/JxD++XiA9Ff4F5ZnHxDOxwP9zzB6L80jVhZIgJJjhdpR0HYLCMU94CpVbtUn8MNrSH3LNSkGpTn20RRhYnhKuEV0ySA=,iv:Jo1cLFqW4gHHBEjPTVdiFjp31uqsyTWjgpFuvxoPZpM=,tag:Ayqw48AvDfvEqN0sltb0kA==,type:str]
    pgp:
        - created_at: "2025-01-14T16:42:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwH5G7pFZya3AQ//ae0DpSJK6kbZUj4cXtzyE5jYwC3+AU63vfYiLn3wvpeA
            5hFcAlNqfyB9S2lrsmoZW+5z7XEpdTWu1JbxqSgmAYZzTDxwl54tFhFSNxoo+E9F
            E8M/lV6cYwWom3lro5hq2MJXRgtFQu7acBIhOW2LJF1IHR6Nx4uI9d/KBeMbCsp9
            J7I9Pp9O6SNt6RluzrmsdotdlKqj9TTDdp6mH45yfQ7GqA/rc9Yi4Drq8fYoRloh
            tICUne2z2xrCjLJaH3yXWf1xb3Yb913CEicoLRbMHH1sYFyrefROV/RYgUowUs57
            gSenQqpcsn2qb2LFTedxM/q1wS1AnNIOL41AlW+Ln7PexInoMY6Yk9wP2JskbZ9T
            CEPw6QbbiCIyiMq7QCnJgWrTPKvacT28rDQK4z/Yy9ymF6bwIlslV5QESBQ6rdop
            nf9TzWu/5JJxopq4fGQiNH2Jrf5MTCxCy0oUMU/4SsGQTSpWvf1qSw6EwEqmROqp
            DxkhuCtpXdIaINwqocXca8Bz9G8rH4y9W3iE7W5g2WWfxkoXOLAKcY18s14gWJ+C
            1helyf7vAzjzk3KIYZye00x1f2ZItjVlI+nDKEgV7GnSxpM8ucX+ZCqzISiuJKNT
            yCfJmbx5ufq0kbYAfVwAyAeR+cqgOCp12ol1pf+57MB9/Ay8vOBnpVoXS5eeNZfU
            aAEJAhCeDiFlbkazmqUQdS4o/0m5VaZ2F32jM8/LfvNvEI/2t1FSbiaWgoTz4N2g
            PdXjcxNVPXyYCqHFN4J0eW0pg3Kl6Dyfw5TLL/z6YzexXAJiLa3KjwfUVeKeOqJF
            7MkWwRyfgurH
            =t2cC
            -----END PGP MESSAGE-----
          fp: 880EAC2E7DC18ECCD2D848059CA459D0DA8B1A5E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
