apiVersion: v1
kind: ServiceAccount
metadata:
  name: octavia-creator-sa
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: octavia-creator-role
  namespace: openstack
rules:
- apiGroups: [""] 
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list" ] 
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get"]
- apiGroups: ["openstack.k-orc.cloud"]
  resources: ["securitygroups", "flavors", "networks"]
  verbs: ["get"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: octavia-creator-rb
  namespace: openstack
subjects:
- kind: ServiceAccount
  name: octavia-creator-sa
roleRef:
  kind: Role
  name: octavia-creator-role
  apiGroup: rbac.authorization.k8s.io