---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: openvswitch-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml