images:
  tags:
    openvswitch_db_server: quay.io/airshipit/openvswitch:latest-${OPENSTACK_DIST}
    openvswitch_vswitchd: quay.io/airshipit/openvswitch:latest-${OPENSTACK_DIST}
conf:
  ovs_user_name: ""