apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
resources:
  - helmrepository.yaml
  - keystone
  - heat
  - glance
  - cinder
  - openvswitch
  - libvirt
  - placement
  - nova
  - neutron
  - barbican
  - octavia
  - horizon
  - gnocchi
  - aodh
  - ceilometer
  - skyline