apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podmonitors.yaml
  - thanos
  - loki
  - alloy
  - prometheus-openstack-exporter
  - prometheus-process-exporter
  - prometheus-mysql-exporter
  - prometheus-blackbox-exporter