---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
resources:
  - secrets.yaml
  - network.yaml
  - subnet.yaml
  - securitygroup.yaml
  - port.yaml
  - flavor.yaml
  - image.yaml
