apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: lb-mgmt-net
  namespace: openstack  
spec:
  cloudCredentialsRef:
    cloudName: cloudname
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: |
      Octavia management network
    tags:
    - octavia