apiVersion: v1
kind: Secret
metadata:
    name: openstack-clouds
    namespace: openstack
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      cloudname:
        auth:
          auth_url: https://keystone.openstack.svc.cluster.local/v3
          username: admin
          password: "${keystone_admin_password}"
          project_name: admin
          user_domain_name: Default
          project_domain_name: Default
        region_name: "RegionOne"
        identity_api_version: '3'
        volume_api_version: '3'
        verify: false